apiVersion: v1
kind: Service
metadata:
  name: {{ template "pdns.fullname" . }}-api
  namespace: {{ .Release.Namespace }}  
  labels:
    app: {{ template "pdns.name" . }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ip }}
  loadBalancerIP: {{ .Values.service.ip }}
  {{- end}}
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: api
  selector:
    app: {{ template "pdns.name" . }}
    release: {{ .Release.Name }}
