apiVersion: v2
name: powerdns
description: A Helm chart to deploy PowerDNS to Kubernetes
version: 1.0.0
appVersion: 4
keywords:
  - dns
home: https://puckpuck.com
dependencies:
- name: mariadb
  version: 7
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
sources:
  - https://github.com/PowerDNS/pdns
icon: https://github.com/puckpuck/helm-charts/tree/master/powerdns/powerdns.png
maintainers:
  - name: puckpuck
    email: pierre@pierretessier.com
