{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "seashell.fullname" . }}
  labels:
  {{- include "seashell.labels" . | nindent 4 }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  {{- if .Values.rbac.readAll }}
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
  {{- end }}
  {{- with .Values.rbac.extraRules }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
